spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swipe_cicd_test?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: david_ISAIAH_1234#$
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1500MB
      max-request-size: 1500MB
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss


  application:
    name: account-micro-service
  boot:
    admin:
      url: http://localhost:2031/
      #spring.boot.admin.client.url=http://localhost:6060/
      #spring.boot.admin.client.username=admin
      #spring.boot.admin.client.password=admin
      #client:
      #username: swipe_user
      #password: swipe_password
      #instance:
      #metadata:
      #user.name: swipe_user
      #user.password: swipe_password
file:
  upload-dir: ./temp/uploads

server:
  port: 2021
  servlet:
    contextPath: /account

eureka:
  client:
    registryFetchIntervalSeconds: 5
    enabled: true
    service-url:
      defaultZone: http://localhost:2020/eureka
    instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 10
      health-check-url-path: /actuator/health
      metadata-map:
        startup: ${random.int}    #needed to trigger info and endpoint update after restart
      #metadata-map:
      #user.name: swipe_user
      #user.password: swipe_password

  instance:
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator



logging:
  file:
    name: account_micro_service.log
    max-history: 5
    max-size: 20MB

management:
  security:
    enable: false
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

security:
  basic:
    enabled: false